name: test

on: push

jobs:
  lib:
    name: lib
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Run install
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run type check
        run: npm run type

      - name: Run build
        run: npm run build
